[manifest]
version = "1.0.0"
dump_lua = true
priority = 0

# Being saved by a joker says "Revive!" instead of "Saved by Mr Bones".
[[patches]]
[patches.pattern]
target = "functions/common_events.lua"
pattern = "{n=G.UIT.O, config={object = DynaText({string = {' '..localize('ph_mr_bones')..' '}, colours = {G.C.FILTER}, shadow = true, pop_in = 0, scale = 0.5*scale, silent = true})}}"
position = "at"
payload = '''{n=G.UIT.O, config={object = DynaText({string = {' Revive! '}, colours = {G.C.FILTER}, shadow = true, pop_in = 0, scale = 0.5*scale, silent = true})}}'''
match_indent = true
overwrite = true
